# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\juantorres\TOTAL\PYTHON\TP2FINAL\tempUI.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1036, 485)
        Dialog.setSizeGripEnabled(True)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(260, 160, 111, 31))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 180, 151, 61))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(180, 160, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 120, 71, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(-200, 500, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(260, 200, 111, 31))
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 200, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(260, 120, 111, 31))
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.label.setObjectName("label")
        self.textEdit_7 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_7.setGeometry(QtCore.QRect(10, 120, 101, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 90, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.mdiArea = QtWidgets.QMdiArea(Dialog)
        self.mdiArea.setGeometry(QtCore.QRect(260, 90, 21, 21))
        self.mdiArea.setObjectName("mdiArea")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.mdiArea_2 = QtWidgets.QMdiArea(Dialog)
        self.mdiArea_2.setGeometry(QtCore.QRect(500, 90, 21, 21))
        self.mdiArea_2.setObjectName("mdiArea_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 200, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit_6 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_6.setGeometry(QtCore.QRect(500, 120, 111, 31))
        self.textEdit_6.setReadOnly(True)
        self.textEdit_6.setObjectName("textEdit_6")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 120, 71, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit_9 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_9.setGeometry(QtCore.QRect(500, 160, 111, 31))
        self.textEdit_9.setReadOnly(True)
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_10.setGeometry(QtCore.QRect(500, 200, 111, 31))
        self.textEdit_10.setReadOnly(True)
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(430, 90, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(420, 160, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.mdiArea_3 = QtWidgets.QMdiArea(Dialog)
        self.mdiArea_3.setGeometry(QtCore.QRect(740, 90, 21, 21))
        self.mdiArea_3.setObjectName("mdiArea_3")
        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setGeometry(QtCore.QRect(90, 30, 151, 31))
        self.textEdit_5.setReadOnly(True)
        self.textEdit_5.setObjectName("textEdit_5")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(660, 200, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.textEdit_11 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_11.setGeometry(QtCore.QRect(740, 200, 111, 31))
        self.textEdit_11.setReadOnly(True)
        self.textEdit_11.setObjectName("textEdit_11")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(660, 160, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit_12 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_12.setGeometry(QtCore.QRect(740, 160, 111, 31))
        self.textEdit_12.setReadOnly(True)
        self.textEdit_12.setObjectName("textEdit_12")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(660, 120, 71, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.textEdit_8 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_8.setGeometry(QtCore.QRect(740, 120, 111, 31))
        self.textEdit_8.setReadOnly(True)
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(670, 90, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.mdiArea_4 = QtWidgets.QMdiArea(Dialog)
        self.mdiArea_4.setGeometry(QtCore.QRect(400, 80, 21, 161))
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea_4.setBackground(brush)
        self.mdiArea_4.setObjectName("mdiArea_4")
        self.mdiArea_5 = QtWidgets.QMdiArea(Dialog)
        self.mdiArea_5.setGeometry(QtCore.QRect(640, 80, 21, 161))
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea_5.setBackground(brush)
        self.mdiArea_5.setObjectName("mdiArea_5")
        self.mdiArea_6 = QtWidgets.QMdiArea(Dialog)
        self.mdiArea_6.setGeometry(QtCore.QRect(160, 80, 21, 161))
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea_6.setBackground(brush)
        self.mdiArea_6.setObjectName("mdiArea_6")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(350, 25, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 451, 91))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "GetTemp1"))
        self.pushButton_2.setText(_translate("Dialog", "SetTemp1"))
        self.pushButton_3.setText(_translate("Dialog", "GetValve1"))
        self.label.setText(_translate("Dialog", "Logs Commandes "))
        self.label_2.setText(_translate("Dialog", "Command Input"))
        self.label_3.setText(_translate("Dialog", "Serveur 1"))
        self.comboBox.setItemText(0, _translate("Dialog", "Serveur1"))
        self.comboBox.setItemText(1, _translate("Dialog", "Serveur2"))
        self.comboBox.setItemText(2, _translate("Dialog", "Serveur3"))
        self.label_4.setText(_translate("Dialog", "Main Selector"))
        self.pushButton_4.setText(_translate("Dialog", "GetValve2"))
        self.pushButton_5.setText(_translate("Dialog", "SetTemp2"))
        self.textEdit_9.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "Serveur 2"))
        self.pushButton_6.setText(_translate("Dialog", "GetTemp2"))
        self.pushButton_7.setText(_translate("Dialog", "GetValve3"))
        self.pushButton_8.setText(_translate("Dialog", "GetTemp3"))
        self.textEdit_12.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_9.setText(_translate("Dialog", "SetTemp3"))
        self.label_8.setText(_translate("Dialog", "Serveur 3"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; text-decoration: underline; color:#1e5e01;\">Temperature Command Central</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; text-decoration: underline; color:#c8091c;\">UFR Sciences et techniques-ESE-M2</span></p><p><span style=\" font-size:11pt; font-style:italic; text-decoration: underline; color:#3214c8;\">Professeur: MAHMOUD Addouche</span></p><p><span style=\" font-size:11pt; font-style:italic; text-decoration: underline; color:#3214c8;\">Auteurs: TORRES ZETINO Juan Carlos et RACHID Moussa</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

